version: '3.7'
services:
  postgres:
    image: postgres:14
    environment:
      - POSTGRES_DB=network_metadata_trial
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    networks:
      - default

  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
      target: local
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
     - ENVIRONMENT=local
     - AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN}
     - AWS_REGION=${AWS_REGION}
     - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
     - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
     - AWS_SECURITY_TOKEN=${AWS_SECURITY_TOKEN}
    depends_on:
      - postgres
