# Generated by Django 4.1 on 2022-11-01 15:30

import api.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Member",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("organizationId", models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="MemberProfile",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.member"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MemberProfileFulfillmentModel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("active", models.BooleanField(default=False)),
                (
                    "memberProfile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.memberprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="NetworkFulfillmentModel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=256, unique=True)),
                ("definition", models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name="NetworkMemberProfileType",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            (
                                api.models.NetworkMemberProfileTypes["RETAILER"],
                                "RETAILER",
                            ),
                            (
                                api.models.NetworkMemberProfileTypes[
                                    "THIRD_PARTY_LOGISTICS"
                                ],
                                "3PL",
                            ),
                        ],
                        max_length=50,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="NetworkVertical",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=256, unique=True)),
                ("definition", models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name="RequirementType",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[("GENERAL_NOTE", "General Note")],
                        max_length=50,
                        unique=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MemberProfileVersion",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("active", models.BooleanField(default=False)),
                ("name", models.CharField(max_length=100)),
                ("description", models.CharField(max_length=256)),
                ("createdDate", models.DateTimeField(auto_now_add=True)),
                ("createdBy", models.CharField(max_length=256)),
                ("version", models.CharField(max_length=4)),
                ("snapshot", models.CharField(max_length=1024)),
                (
                    "memberProfile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.memberprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MemberProfileProgram",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=256)),
                ("active", models.BooleanField(default=False)),
                (
                    "memberProfileFulfillmentModel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.memberprofilefulfillmentmodel",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MemberProfileFulfillmentModelRequirement",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("detail", models.JSONField(max_length=1024)),
                ("active", models.BooleanField(default=False)),
                (
                    "memberProfileFulfillmentModel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.memberprofilefulfillmentmodel",
                    ),
                ),
                (
                    "requirementType",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.requirementtype",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="memberprofilefulfillmentmodel",
            name="networkFulfillmentModel",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="api.networkfulfillmentmodel",
            ),
        ),
        migrations.AddField(
            model_name="memberprofilefulfillmentmodel",
            name="networkVertical",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.networkvertical",
            ),
        ),
        migrations.CreateModel(
            name="MemberProfileDraft",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.CharField(max_length=256)),
                ("createdDate", models.DateTimeField(auto_now_add=True)),
                ("createdBy", models.CharField(max_length=256)),
                ("majorVersion", models.CharField(max_length=4)),
                ("minorVersion", models.CharField(max_length=4)),
                ("snapshot", models.JSONField(max_length=1024)),
                (
                    "memberProfile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.memberprofile",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="memberprofile",
            name="profileType",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="api.networkmemberprofiletype",
            ),
        ),
    ]
